### ISSUE TITLE
Vanilla Tweaks Name Colors not restored when player becomes motile

### ISSUE THREAD

**Issue by Tikkle** [bytzo/sessility#2] opened 2022-09-27 18:46 UTC
Hello there!

My name's Tikkle, or Tik, and I'd like to request that the last team the player is on be stored when the player goes AFK. That way when they un-AFK it returns them to the previous team.

I ask this because VanillaTweaks' datapack "Colors" uses Minecraft Teams to allow players to choose a custom color for their username that displays in chat and on the tab-list.

Thanks,
Tik

**EDIT:** It seems to restore "colors" team the player was on if the player is OP'd.

**Comment by bytzo** [comment] 2022-09-27 20:55
Thanks for the request! However, Sessility doesn't mess with teams, so team colors shouldn't be affected. Perhaps you have the Vanilla Tweaks AFK Display data pack enabled?

**Comment by Tikkle** [comment] 2022-09-27 23:27
I didn't use the VT AFK display because I thought it might effect the colors datapack. The only 2 items I have that modify username colors are Sessility and Colors DP. :)

**Comment by bytzo** [comment] 2022-09-28 00:25
Would you be able to send a full list of the mods and data packs you are using? I am unable to reproduce this issue on my machine, so there might be a mod conflict.

**Comment by Tikkle** [comment] 2022-09-28 16:46
**Mods:**
Alternate Current, Armor Stand Editor, AutoWhitelist, Cloth Config, dcintegration (discord chat+mc chat), fabic api, fabric kotlin, ferritecore, krypton, lazydfu, lithium, midnightlib, nochatreports, repurposed structures, sessility, simply no report, starlight, timeoutout, wither-cage-fix

**Datapacks:**
BlazeandCaves Advancements Pack 1.15.zip, anti enderman grief v1.1.3.zip, custom nether portals v2.3.6.zip, double shulker shells v1.3.3.zip, more mob heads v2.10.1.zip, name colors v1.0.1.zip, nether portal coords v1.1.3.zip, silence mobs v1.1.3.zip, unlock all recipes v2.0.4.zip, villager workstation highlights v1.1.3.zip

**Comment by bytzo** [comment] 2022-09-29 01:10
Even with those mods and data packs, I was still unable to reproduce the issue. At this point, you'll need to do some of the troubleshooting on your end. Here are the steps I would take:

1. Create a process to reliably trigger the issue. You will use this process many times in the following steps to check if the issue occurs or not.
2. Verify that the issue occurs when only Sessility and the name colors data pack are installed. Use a fresh Minecraft world and server configuration.
    - If the issue still occurs, Sessility is causing the issue. Skip to step 4.
    - If the issue doesn't occur, another mod or your server configuration is causing the issue. Switch back to the Minecraft world and server where the issue was occurring and proceed to the next step to perform a bisect.
3. A bisect helps narrow down mods or data packs that may be causing the issue. Perform the following steps with mods, then data packs if necessary.
    - Disable about half of the mods/data packs (excluding Sessility and the name colors data pack). When disabling mods, ensure you keep dependent mods together (for example, many mods rely on the Fabric API, so ensure the Fabric API is always enabled with the mods  that need it)
    - Then: 
        - If the issue still occurs, the issue is being caused by one of the currently enabled mods. Disable about half of the mods/data packs again (excluding Sessility and the name colors data pack).
        - If the issue doesn't occur, the issue was caused by one of the disabled mods. Disable all the enabled mods/data packs (excluding Sessility and the name colors data pack) and re-enable the previously disabled mods. The issue should occur again. Disable about half of the mods you just re-enabled.
    - Repeat the step above until you have singled out a single mod/data pack that is causing the issue.
4. Report your findings. Please include the following information:
    - The latest server log of a session where the issue occurred.
    - The output of `/datapack list`
    - If you used a bisect, the mod or data pack that caused the issue.
    - If you used a bisect, the configuration file of the mod causing the issue (if applicable).
    - The process you used to reproduce and identify the issue. (for example: 1. Launch server with Sessility and name colors data pack. 2. Join the server as a normal member, run `/trigger color`, and select "Pink". Your name should turn pink in the player tab list. 3. Stay idle for 120 seconds to become sessile. Your name should turn gray in the player tab list. 4. Move around to become motile. Your name should turn back to pink, but instead becomes white.)
    - (optional) A screen recording of the issue occurring on the client.

**Comment by bytzo** [comment] 2022-10-30 00:46
Hey there, just checking in on the issue. Have you had any luck troubleshooting this recently?

**Comment by bytzo** [comment] 2023-02-02 05:29
Since I've been unable to reproduce this and haven't received any additional information, I will be closing this issue for now. If you have any more information that may help in reproducing the issue, feel free to add a comment and I'll try looking into this again.

**Closed as not planned by bytzo** 2023-02-02 05:29 UTC
